[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_factory = "4vx3swKUwrx7T6NRKXkQfWjVJmAfjUsbsJdLj1GsoPY9"

[programs.devnet]
nft_factory = "4vx3swKUwrx7T6NRKXkQfWjVJmAfjUsbsJdLj1GsoPY9"

[programs.testnet]
nft_factory = "4vx3swKUwrx7T6NRKXkQfWjVJmAfjUsbsJdLj1GsoPY9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
